### ISSUE TITLE
why add this breaking chang in this version

### ISSUE THREAD

**Issue by mochen666** [bubkoo/html-to-image#365] opened 2023-01-31 07:53 UTC
![image](https://user-images.githubusercontent.com/13551778/215699394-e3779297-85ac-43dd-9bc2-eee1b707bf2c.png)

**Comment by bubkoo** [comment] 2023-01-31 09:38
@mochen666 Why it's a breaking chang?

**Comment by TouqeerH** [comment] 2023-01-31 11:29
> @mochen666 Why it's a breaking change?

This change is breaking `yarn`. As it requires `pnpm` which many of us do not use.

**Comment by Fawwad-Khan** [comment] 2023-01-31 11:41
Also facing the same issue.

**Comment by txemaleon** [comment] 2023-01-31 12:19
Hi!

Also facing this

The problem is your `pre-install` hook is running `npx only-allow pnpm` which breaks installs on packages dependant on `html-to-image`.

While I understand this is good intentioned, I'd appreciate if you could revert the change in the `pre-install` hook, as it is not needed after publishing the package and it's effectively prohibiting the installation in every non-pnpm environment.

Thanks! Hope this helps you

**Comment by thealonekhan** [comment] 2023-01-31 12:52
Facing same issue

**Comment by carlosg-ordering** [comment] 2023-01-31 16:57
Same here

**Comment by chrislondon** [comment] 2023-01-31 20:21
same here

**Comment by ddelpiano** [comment] 2023-01-31 20:44
same here

**Comment by sandi-buchanan** [comment] 2023-02-01 14:57
Same issue being encountered in our project.

**Comment by txemaleon** [comment] 2023-02-01 15:53
If anyone gets here trough google, you have to update to v`1.11.10` at least to fix this problema

**Comment by bubkoo** [comment] 2023-02-02 02:36
v1.11.9 was marked as deprecated.

![image](https://user-images.githubusercontent.com/6045824/216217166-aae50568-ba4f-4163-9f1b-40b4a73fbef3.png)

**Closed** 2023-02-09 04:32 UTC
Labels: bug
